<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20859" started-at="2018-06-25T08:32:05Z" finished-at="2018-06-25T08:32:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20859" started-at="2018-06-25T08:32:05Z" finished-at="2018-06-25T08:32:26Z">
      <class name="HotZone.autotest.testCases.TC_APP_ValidAndInvalidLogin">
        <test-method status="PASS" signature="setup()[pri:0, instance:HotZone.autotest.testCases.TC_APP_ValidAndInvalidLogin@17d0685f]" name="setup" is-config="true" duration-ms="18597" started-at="2018-06-25T16:32:05Z" finished-at="2018-06-25T16:32:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="testInvalidLoginWithWrongEmail()[pri:0, instance:HotZone.autotest.testCases.TC_APP_ValidAndInvalidLogin@17d0685f]" name="testInvalidLoginWithWrongEmail" duration-ms="16" started-at="2018-06-25T16:32:23Z" finished-at="2018-06-25T16:32:23Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at HotZone.autotest.pageObjects.LoginPageObject.verify_email_page_header(LoginPageObject.java:42)
	at HotZone.autotest.testCases.TC_APP_ValidAndInvalidLogin.testInvalidLoginWithWrongEmail(TC_APP_ValidAndInvalidLogin.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidLoginWithWrongEmail -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:HotZone.autotest.testCases.TC_APP_ValidAndInvalidLogin@17d0685f]" name="teardown" is-config="true" duration-ms="2219" started-at="2018-06-25T16:32:23Z" finished-at="2018-06-25T16:32:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- HotZone.autotest.testCases.TC_APP_ValidAndInvalidLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
